apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc 
  labels:
    serviceName: api-gateway-svc 
spec:
  type: {{ .Values.service.apiGateway.type }}
  ports:
    - nodePort: {{ .Values.service.apiGateway.port }}
      targetPort: 9000
      protocol: TCP
      name: http
      port: 9000
  selector:
    serviceName: api-gateway-svc 
