apiVersion: v1
kind: Service
metadata:
  name: match-svc 
  labels:
    serviceName: match-svc 
spec:
  type: {{ .Values.service.match.type }}
  ports:
    - port: {{ .Values.service.match.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    serviceName: match-svc 
