apiVersion: v1
data:
  player-service.properties: |
    server.port: 8083
    server.servlet.context-path=/player-service
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://{{.Values.mysql.host}}:63306/fantasy_league
    spring.datasource.username=root
    spring.datasource.password=root
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    spring.jpa.show-sql=true
    spring.devtools.restart.log-condition-evaluation-delta=false
    spring.jackson.mapper.default-view-inclusion=true
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: player-properties-configmap
