apiVersion: v1
kind: Service
metadata:
  name: player-svc 
  labels:
    serviceName: player-svc 
spec:
  type: {{ .Values.service.player.type }}
  ports:
    - port: {{ .Values.service.player.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    serviceName: player-svc 
