apiVersion: v1
kind: Service
metadata:
  name: ui-svc 
  labels:
    serviceName: ui-svc 
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }} 
      targetPort: 80
      protocol: TCP
      name: http
      #nodePort: {{ .Values.service.ui.port }}
  selector:
    serviceName: ui-svc 
