apiVersion: v1
kind: Service
metadata:
  name: user-svc 
  labels:
    serviceName: user-svc 
spec:
  type: {{ .Values.service.user.type }}
  ports:
    - port: {{ .Values.service.user.port }}
      targetPort: {{ .Values.service.user.port }}
      protocol: TCP
      name: http
  selector:
    serviceName: user-svc 
