# Default values for fantasy-league.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
mysql:
  host: 192.168.1.2 
eureka:
  image:
    name: eureka-server
    pullPolicy: Never 
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"

match:
  image:
    name: match-service
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"

team:
  image:
    name: team-service
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"
imagePullSecrets: []

player:
  image:
    name: player-service
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"

user:
  image:
    name: user-service
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"

apiGateway:
  image:
    name: api-gateway
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"
ui:
  image:
    name: ui-app
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0"
podAnnotations: {}


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  eureka:
    type: ClusterIP
    port: 8761
  match:
    type: ClusterIP
    port: 8084
  team:
    type: ClusterIP
    port: 8082
  player:
    type: ClusterIP
    port: 8083
  user:
    type: ClusterIP
    port: 8081
  ui:
    type: ClusterIP
    port: 4200
  apiGateway:
    type: NodePort
    port: 30081
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
